import pyautogui, time

gangnam = [
"Oppan Gangnam Style",
"Gangnam Style",
"Najeneun ddasarowun in-ganjeogin yeoja",
"Keopi hanjaneui yeoyureul aneun pumgyeok ittneun yeoja",
"Bami omyeon shimjangi ddeugeowojineun yeoja",
"Geureon banjeon ittneun yeoja",
"Naneun sanai",
"Najeneun neomankeum ddasarowun geureon sanai",
"Keopi shik-gido jeone One Shot ddaerineun sanai",
"Bami omyeon shimjangi teojyeobeorineun sanai",
"Geureon sanai",
"Aremdawo sarangseurowo",
"Geurae neo hey, geurae baro neo hey",
"Areumdawo sarangseurowo",
"Geurae neo hey, geurae baro neo hey",
"Jigeumbuteo gal ddaekkaji gabolkka",
"Oppan Gangnam style",
"Gangnam style",
"Oppan Gangnam style",
"Gangnam style",
"Oppan Gangnam style",
"Eh Sexy Lady",
"Oppan Gangnam style",
"Eh Sexy Lady",
"Eh, eh, eh, eh, eh, eh",
"Jeongsokhae bo-ijiman nol ddaen noneun yeoja",
"Iddaeda shipeumyeon mukkeottdeon meori puneun yeoja",
"Garyeottjiman wenmanhan nochulboda yahan yeoja",
"Geureon gangjakjeogin yeoja",
"Naneun sanai",
"Jeonjanha bo-ijiman nol ddaen noneun sanai",
"Ddaega dweimyeon wanjeon michyeobeorineun sanai",
"Geun-yukboda sasangi ultungbultung han sanai",
"Geureon sanai",
"Aremdawo sarangseurowo",
"Geurae neo hey, geurae baro neo hey",
"Areumdawo sarangseurowo",
"Geurae neo hey, geurae baro neo hey",
"Jigeumbuteo gal ddaekkaji gabolkka",
"Oppan Gangnam style",
"Gangnam style",
"Oppan Gangnam style",
"Gangnam style",
"Oppan Gangnam style",
"Eh Sexy Lady",
"Oppan Gangnam style",
"Eh Sexy Lady",
"Eh, eh, eh, eh, eh, eh",
"Ttwineun nom geu wi-e naneun nom",
"Baby baby",
"Naneun mwol jom aneun nom",
"Ttwineun nom geu wi-e naneun nom",
"Baby baby",
"Naneun mwol jom aneun nom",
"You know what I'm saying",
"Oppan Gangnam style",
"Eh Sexy Lady",
"Oppan Gangnam style",
"Eh Sexy Lady",
"Oppan Gangnam style",
]

#Spammer
time.sleep(5)
#Change variable to chosen option
for word in gangnam:
    pyautogui.typewrite(word)
    time.sleep(0.5)
    pyautogui.press("enter")
    time.sleep(0.5)
